### np.ogrid

In [1]:
import numpy as np

height, width = 3, 4
y, x = np.ogrid[:height, :width]

In [2]:
y, x

(array([[0],
        [1],
        [2]]),
 array([[0, 1, 2, 3]]))

使用 ogrid 的最大好处是利用 NumPy 的 广播机制 (Broadcasting)。当你对 x 和 y 进行运算时（例如 x + y），NumPy 会自动把它们“扩充”成完整的 $3 \times 4$ 矩阵，而不需要在内存中显式地创建这两个大矩阵。
$$
\begin{bmatrix} 0 \\ 1 \\ 2 \end{bmatrix} + \begin{bmatrix} 0 & 1 & 2 & 3 \end{bmatrix} = \begin{bmatrix} 0 & 1 & 2 & 3 \\ 1 & 2 & 3 & 4 \\ 2 & 3 & 4 & 5 \end{bmatrix}
$$

In [3]:
y + x

array([[0, 1, 2, 3],
       [1, 2, 3, 4],
       [2, 3, 4, 5]])